create table if not exists public.badges (
    id bigint generated by default as identity primary key,

    name text not null,
    description text,
    icon_url text,

    badge_type text not null
        check (
            badge_type in (
                'checkin',
                'journey'
            )
        ),

    requirement_value integer default 1,

    journey_id bigint
        references public.journeys(id)
        on delete cascade,

    is_active boolean default true,

    created_at timestamptz default now()
);

create table if not exists public.user_badges (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references public.profiles(id)
        on delete cascade,

    badge_id bigint not null
        references public.badges(id)
        on delete cascade,

    earned_at timestamptz default now(),

    unique(user_id, badge_id)
);

alter table public.badges
enable row level security;

alter table public.user_badges
enable row level security;

create policy "Badges are public"
on public.badges
for select
using (true);

create policy "Users can view own badges"
on public.user_badges
for select
using (
    auth.uid() = user_id
);

create policy "Users can insert own badges"
on public.user_badges
for insert
with check (
    auth.uid() = user_id
);

insert into public.badges (
    name,
    description,
    badge_type,
    requirement_value
)
values (
    'Nhà khám phá đầu tiên',
    'Check-in thành công địa điểm đầu tiên.',
    'checkin',
    1
);

insert into public.badges (
    name,
    description,
    badge_type,
    requirement_value,
    journey_id
)
values (
    'Nhà khám phá Sài Gòn',
    'Hoàn thành Hành trình Di sản Sài Gòn.',
    'journey',
    1,
    1
);